# Generated by Django 4.0.5 on 2022-06-23 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='description',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
