# Generated by Django 4.0.5 on 2022-06-23 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_likes_likes_unique_like'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='likes',
            name='unique_like',
        ),
        migrations.RenameField(
            model_name='likes',
            old_name='post',
            new_name='blog',
        ),
    ]
