# Generated by Django 4.0.5 on 2022-06-23 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_likes_unique_like_rename_post_likes_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='url',
            field=models.TextField(null=True),
        ),
    ]
